module.exports = {
  ID: "",
  "Criado em": "",
  ES: "",
  Escola: "",
  Titularidade: "",
  Tipo: "",
  Discriminação: "",
  "Local do movimento": "",
  Valor: "",
  "Forma de pagamento": "",
  Vencimento: "",
  Parcelas: 1,
  Observações: "",
  "Pago em": "",
  "Atualizado em": "",
  "Outras Observações": "",
  "Titular Cheque": "",
  "Conta Cheque": "",
  "Agência Cheque": "",
  "Nº Cheque": "",
};
